name: Update Streamlit Bot Daily

on:
  schedule:
    - cron: '0 13 * * *' # Every day at 13:00 UTC (9:00 AM EST)

jobs:
  update-streamlit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Streamlit App (Headless Mode)
        run: |
          streamlit run app.py --server.headless true --server.port 8501
